int calculate() {
  return 6 * 7;
}

// TODO(goVishal): complete this design pattern
// 
// Singleton Design Pattern. ...
// Factory Method Design Pattern. ...
// Facade Design Pattern. ...
//  > Strategy Design Pattern / Policy pattern
// Observer Design Pattern. ...
// Builder Design Pattern. ...
// Adapter Design Pattern.
